insta = [['Instagram', 573.0, 'Social media platform', 'United States'],
       ['Cristiano Ronaldo', 508.0, 'Footballer', 'Portugal'],
       ['Lionel Messi', 384.0, 'Footballer', 'Argentina'],
       ['Kylie Jenner', 373.0,
        'Television personality, model and businesswoman',
        'United States'],
       ['Selena Gomez', 361.0, 'Musician, actress, and businesswoman',
        'United States'],
       ['Dwayne Johnson', 351.0, 'Actor and professional wrestler',
        'United States'],
       ['Ariana Grande', 342.0, 'Musician, actress and businesswoman',
        'United States'],
       ['Kim Kardashian', 334.0,
        'Television personality, model and businesswoman',
        'United States'],
       ['Beyoncé', 284.0, 'Musician, actress and businesswoman',
        'United States'],
       ['Khloé Kardashian', 281.0, 'Television personality and model',
        'United States'],
       ['Justin Bieber', 267.0, 'Musician', 'Canada'],
       ['Kendall Jenner', 265.0, 'Model and television personality',
        'United States'],
       ['Nike', 253.0, 'Sportswear multinational', 'United States'],
       ['National Geographic', 247.0, 'Magazine', 'United States'],
       ['Taylor Swift', 234.0, 'Musician and actress', 'United States'],
       ['Jennifer Lopez', 227.0, 'Musician and actress', 'United States'],
       ['Virat Kohli', 225.0, 'Cricketer', 'India'],
       ['Nicki Minaj', 206.0, 'Musician',
        'Trinidad and Tobago United States'],
       ['Kourtney Kardashian', 204.0, 'Television personality and model',
        'United States'],
       ['Neymar', 189.0, 'Footballer', 'Brazil'],
       ['Miley Cyrus', 188.0, 'Musician and actress', 'United States'],
       ['Katy Perry', 181.0, 'Musician', 'United States'],
       ['Zendaya', 160.0, 'Actress and singer', 'United States'],
       ['Kevin Hart', 159.0, 'Comedian and actor', 'United States'],
       ['Cardi B', 144.0, 'Musician and actor', 'United States'],
       ['Demi Lovato', 143.0, 'Musician and actor', 'United States'],
       ['Rihanna', 138.0, 'Musician and businesswoman', 'Barbados'],
       ['LeBron James', 138.0, 'Basketball player', 'United States'],
       ['Real Madrid CF', 128.0, 'Football club', 'Spain'],
       ['Ellen DeGeneres', 128.0, 'Comedian and television personality',
        'United States'],
       ['Drake', 126.0, 'Musician', 'Canada'],
       ['Chris Brown', 125.0, 'Musician', 'United States'],
       ['FC Barcelona', 114.0, 'Football club', 'Spain'],
       ['Billie Eilish', 107.0, 'Musician', 'United States'],
       ['UEFA Champions League', 100.0, 'Club football competition',
        'Europe'],
       ['Gal Gadot', 91.3, 'Actress', 'Israel'],
       ['Dua Lipa', 87.4, 'Musician', 'United Kingdom Albania'],
       ['NASA', 85.3, 'Space agency', 'United States'],
       ['Lisa', 84.9, 'Musician', 'Thailand'],
       ['Vin Diesel', 84.7, 'Actor', 'United States'],
       ['Priyanka Chopra', 83.8, 'Actress and musician', 'India'],
       ['Khaby Lame', 80.3, 'Social media personality',
        'Italy Senegal'],
       ['Snoop Dogg', 78.2, 'Musician', 'United States'],
       ['Shakira', 77.6, 'Musician', 'Colombia'],
       ['Shraddha Kapoor', 76.4, 'Actress', 'India'],
       ['Gigi Hadid', 76.3, 'Model', 'United States'],
       ['David Beckham', 76.0, 'Footballer', 'United Kingdom'],
       ['Kylian Mbappé', 75.2, 'Footballer', 'France'],
       ["Victoria's Secret", 73.7, 'Lingerie company', 'United States'],
       ['Alia Bhatt', 73.3, 'Actress and musician',
        'United Kingdom, India']]
